### PR TITLE
add YandexDisk widget

### PR DESCRIPTION
**Pull request by mrtnvgr**
Originally posted as qtile/qtile#4061

### CODE REVIEW

**Comment by mrtnvgr** [comment]
@elParaguayo

**Comment by elParaguayo** [comment]
Sorry - totally missed this one. 

You don't need the test on `qtile-examples`. There's no CI testing here. Can you remove that then we can merge this.

**Comment by mrtnvgr** [comment]
> Sorry - totally missed this one. 
> 
> You don't need the test on `qtile-examples`. There's no CI testing here. Can you remove that then we can merge this.

I think this test can stay as an example how tests can be written. What do you think?

**Comment by mrtnvgr** [comment]
I had already changed the path to the widget in the test so that it can be run independently.

```bash
$ pytest test_yandexdisk.py
```

**Comment by elParaguayo** [comment]
> > Sorry - totally missed this one.
> > You don't need the test on `qtile-examples`. There's no CI testing here. Can you remove that then we can merge this.
> 
> I think we can keep it as an example of how tests can be written. What do you think?

Examples of how to write tests should be in our docs, not here. This is a place to share things that people have created. A test isn't really appropriate here.

**Pull request merged**
